spring.application.name=demo

# Configuración dinámica de Puerto (Vital para Railway)
server.port=${PORT:8080}

# Configuración de Base de Datos (Railway rellena estas variables solo)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finanzas_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:alejandro}

# Hibernate y SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Limita el número de conexiones simultáneas (HikariCP)
# Por defecto son 10, pero en un plan gratuito 4 o 5 es más que suficiente
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Evitar errores de fechas

#spring.jackson.serialization.write-dates-as-timestamps=false
