spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/finanzas_db
spring.datasource.username=postgres
spring.datasource.password=alejandro

# Esto crea las tablas automáticamente basado en tu código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Esto asegura que use las funciones específicas de Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formato de fechas para que no den problemas con LocalDate
#spring.jackson.serialization.write-dates-as-timestamps=false