spring.application.name=demo

# Configuración dinámica de Puerto (Vital para Railway)
server.port=${PORT:8080}

# Configuración de Base de Datos (Railway rellena estas variables solo)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finanzas_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:alejandro}

# Hibernate y SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Evitar errores de fechas

#spring.jackson.serialization.write-dates-as-timestamps=false